// electron/main.cjs
// Electron main process entry point (with startup patch window)

const { app, BrowserWindow, Menu, ipcMain, globalShortcut, dialog } = require('electron');
const path = require('path');
const fs = require('fs');
const http = require('http');
const net = require('net'); // Added net module for port checking
const { pathToFileURL } = require('url');
const {
  initAutoUpdater,
  checkForUpdates,
  oneClickUpdate,
  getLatestVersionInfo,
} = require('./updateChecker.cjs');
const logger = require('./logger.cjs');

const isDev = !app.isPackaged;
let patchWindow = null;
let mainWindow = null;

// Default location icon settings (for both speech bubble and location pin)
const DEFAULT_LOCATION_ICON_SETTINGS = {
  speechBubble: {
    enabled: true,
    xPercent: 50,
    yPercent: 40,
    size: 96,
    rotation: 0,
    shadow: {
      enabled: true,
      offsetX: 4,
      offsetY: 4,
      blur: 4,
      opacity: 0.5,
    },
    animation: {
      enabled: true,
      type: "floating",
      duration: 2.2,
      amplitude: 18,
    },
  },
  location: {
    enabled: true,
    xPercent: 50,
    yPercent: 50,
    size: 72,
    rotation: 0,
    shadow: {
      enabled: true,
      offsetX: 4,
      offsetY: 4,
      blur: 4,
      opacity: 0.5,
    },
  },
};

// Default ShopList layout (columns and rows per column for each floor)
const DEFAULT_FLOOR_LAYOUT = {
  '1F': { columns: 3, rowsPerCol: 20 },
  '2F': { columns: 2, rowsPerCol: 19 },
  '3F': { columns: 3, rowsPerCol: 20 },
  '4F': { columns: 2, rowsPerCol: 18 },
};

// Hook up logger to renderer
logger.onLog((entry) => {
  // Debug logs are already filtered out in logger.cjs (notifyListeners)
  // but we keep a safety check here or for other potential sources
  if (entry.level === 'debug') return;

  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('debug:log', entry);
  }
});

// Default Genre Mappings (Japanese -> English + Colors)
const DEFAULT_GENRE_MAPPINGS = {
  "ファッション": {
    labelEn: "Fashion",
    headerTextColor: "#00ade4",
    headerBorderColor: "#00ade4",
    rowBackgroundColor: "rgba(193, 235, 246, 0.5)",
  },
  "ファッション雑貨": {
    labelEn: "Fashion Goods",
    headerTextColor: "#40b93c",
    headerBorderColor: "#40b93c",
    rowBackgroundColor: "rgba(182, 226, 142, 0.5)",
  },
  "雑貨": {
    labelEn: "Goods",
    headerTextColor: "#475eb4",
    headerBorderColor: "#475eb4",
    rowBackgroundColor: "rgba(182, 183, 226, 0.5)",
  },
  "飲食店・食品": {
    labelEn: "Food & Beverage",
    headerTextColor: "#f47216",
    headerBorderColor: "#f47216",
    rowBackgroundColor: "rgba(252, 206, 120, 0.5)",
  },
  "サービス": {
    labelEn: "Services",
    headerTextColor: "#ef2f5a",
    headerBorderColor: "#ef2f5a",
    rowBackgroundColor: "rgba(248, 164, 171, 0.5)",
  },
};

// Default configuration for new genres (fallback)
const DEFAULT_GENRE_CONFIG = {
  labelEn: "",
  headerTextColor: "#ffffff",
  headerBorderColor: "#ffffff",
  rowBackgroundColor: "rgba(255, 255, 255, 0.1)",
};

// Load bundled default settings if available (generated by npm run export-settings)
let bundledDefaults = {};
try {
  const defaultsPath = path.join(__dirname, 'default-settings.json');
  if (fs.existsSync(defaultsPath)) {
    bundledDefaults = JSON.parse(fs.readFileSync(defaultsPath, 'utf-8'));
    console.log('Loaded bundled default settings from default-settings.json');
  }
} catch (e) {
  console.warn('Failed to load bundled default settings', e);
}

const INITIAL_LOCATION_ICON_SETTINGS = bundledDefaults.locationIcons || DEFAULT_LOCATION_ICON_SETTINGS;
const INITIAL_FLOOR_LAYOUT = bundledDefaults.floorLayout || DEFAULT_FLOOR_LAYOUT;
const INITIAL_GENRE_MAPPINGS = bundledDefaults.genreMappings || DEFAULT_GENRE_MAPPINGS;

// Prevent multiple instances from starting with a single-instance lock
const gotTheLock = app.requestSingleInstanceLock();
if (!gotTheLock) {
  app.quit();
  return;
}

// On the second launch, it only brings existing windows to the front
app.on('second-instance', () => {
  const win = mainWindow || patchWindow || BrowserWindow.getAllWindows()[0];
  if (win) {
    if (win.isMinimized()) win.restore();
    win.focus();
  }
});

// Determine base renderer URL (Vite dev server or built production files)
const rendererBaseUrl = isDev
  ? 'http://localhost:5173/'
  : `file://${path.join(__dirname, '../dist/index.html')}`;

/**
 * Settings utilities (for persistent configuration: floor + location icons)
 */
function getSettingsPath() {
  return path.join(app.getPath('userData'), 'settings.json');
}

// DEBUG: Track internal state of loadSettings
let lastLoadSettingsDebug = {
  timestamp: null,
  rawPreview: null,
  parsedValue: null,
  parsedType: null,
  checkResult: null,
  finalValue: null,
  error: null
};

function loadSettings() {
  const base = {
    floor: '1F',
    locationIcons: INITIAL_LOCATION_ICON_SETTINGS,
    floorLayout: INITIAL_FLOOR_LAYOUT,
    genreMappings: INITIAL_GENRE_MAPPINGS,
    imageSettings: {
      floorMaps: {
        '1F': '',
        '2F': '',
        '3F': '',
        '4F': '',
      },
      openTimeImage: '',
    },
    // Port ranges for auto-detection (Bridge: 8090-8099, CMS: 8080-8089)
    portRanges: {
      bridge: {
        min: 8090,
        max: 8099,
      },
      cms: {
        min: 8080,
        max: 8089,
      },
    },
    shopSettings: {},
  };

  try {
    const settingsPath = getSettingsPath();
    if (!fs.existsSync(settingsPath)) {
      logger.debug('Settings file does not exist, using defaults');
      return base;
    }

    const raw = fs.readFileSync(settingsPath, 'utf-8');
    const parsed = JSON.parse(raw);

    // Deep merge function to ensure all nested properties are preserved
    const deepMerge = (target, source) => {
      if (!source) return target;
      const result = { ...target };
      
      Object.keys(source).forEach(key => {
        if (source[key] && typeof source[key] === 'object' && !Array.isArray(source[key])) {
          result[key] = deepMerge(target[key] || {}, source[key]);
        } else if (source[key] !== undefined) {
          result[key] = source[key];
        }
      });
      return result;
    };

    const merged = {
      floor: typeof parsed.floor === 'string' ? parsed.floor : base.floor,
      genreMappings: (() => {
        // Deep merge genre mappings with migration logic
        const stored = parsed.genreMappings || {};
        const result = { ...base.genreMappings };
        
        Object.keys(stored).forEach(key => {
          const val = stored[key];
          if (typeof val === 'string') {
            // Migration: convert string (labelEn only) to object with defaults
            result[key] = {
              ...DEFAULT_GENRE_CONFIG,
              labelEn: val,
              // Try to preserve existing color if it matches a default key, otherwise use default white
              ...(DEFAULT_GENRE_MAPPINGS[key] || {}),
              // Ensure labelEn is the stored string
              labelEn: val, 
            };
          } else if (val && typeof val === 'object') {
            // Merge object
            result[key] = {
              ...(result[key] || DEFAULT_GENRE_CONFIG),
              ...val,
            };
          }
        });
        return result;
      })(),
      locationIcons: {
        speechBubble: deepMerge(
          base.locationIcons.speechBubble,
          parsed.locationIcons?.speechBubble || {}
        ),
        location: deepMerge(
          base.locationIcons.location,
          parsed.locationIcons?.location || {}
        ),
      },
      floorLayout: parsed.floorLayout
        ? {
            ...base.floorLayout,
            ...parsed.floorLayout,
          }
        : base.floorLayout,
      imageSettings: parsed.imageSettings
        ? {
            floorMaps: {
              ...base.imageSettings.floorMaps,
              ...parsed.imageSettings.floorMaps,
            },
            openTimeImage: parsed.imageSettings.openTimeImage || base.imageSettings.openTimeImage,
          }
        : base.imageSettings,
      portRanges: parsed.portRanges
        ? {
            bridge: {
              min: typeof parsed.portRanges.bridge?.min === 'number' ? parsed.portRanges.bridge.min : base.portRanges.bridge.min,
              max: typeof parsed.portRanges.bridge?.max === 'number' ? parsed.portRanges.bridge.max : base.portRanges.bridge.max,
            },
            cms: {
              min: typeof parsed.portRanges.cms?.min === 'number' ? parsed.portRanges.cms.min : base.portRanges.cms.min,
              max: typeof parsed.portRanges.cms?.max === 'number' ? parsed.portRanges.cms.max : base.portRanges.cms.max,
            },
          }
        : base.portRanges,
      shopSettings: parsed.shopSettings || base.shopSettings,
    };

    // DEBUG: Record internal state
    lastLoadSettingsDebug = {
      timestamp: new Date().toISOString(),
      rawPreview: raw.substring(0, 100),
      parsedValue: parsed.floor,
      parsedType: typeof parsed.floor,
      checkResult: typeof parsed.floor === 'string',
      finalValue: merged.floor,
      error: null
    };

    logger.info('Settings loaded', {
      floor: merged.floor,
      hasAnimation: !!merged.locationIcons.speechBubble.animation,
      animationEnabled: merged.locationIcons.speechBubble.animation?.enabled,
    });
    return merged;
  } catch (error) {
    // DEBUG: Record error
    lastLoadSettingsDebug = {
      timestamp: new Date().toISOString(),
      error: error.message,
      stack: error.stack
    };
    logger.error('Failed to load settings, using defaults', {
      error: error?.message,
    });
    // Fallback to base defaults on any error
    return base;
  }
}

function saveSettings(partial) {
  const current = loadSettings();
  const next = {
    ...current,
    ...partial,
  };

  try {
    const settingsPath = getSettingsPath();
    fs.writeFileSync(settingsPath, JSON.stringify(next, null, 2), 'utf-8');
    logger.info('Settings saved', {
      floor: next.floor,
    });
  } catch (error) {
    logger.error('Failed to save settings', {
      error: error?.message,
    });
  }

  return next;
}

/**
 * Broadcast floor changes to renderer processes
 */
function broadcastFloor(floor) {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('settings:floor-changed', floor);
  }
}

/**
 * Broadcast floor layout changes to renderer processes
 */
function broadcastFloorLayout(floorLayout) {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('settings:floor-layout-changed', floorLayout);
  }
}

/**
 * Broadcast genre mappings changes to renderer processes
 */
function broadcastGenreMappings(genreMappings) {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('genre-mappings-updated', genreMappings);
  }
}

/**
 * Broadcast shop settings changes to renderer processes
 */
function broadcastShopSettings(shopSettings) {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('shop-settings-updated', shopSettings);
  }
}

/**
 * Update floor layout (per floor) and notify renderer
 * partialLayout: { columns?: number; rowsPerCol?: number }
 */
function updateFloorLayout(floor, partialLayout) {
  const current = loadSettings();
  const prevLayout = current.floorLayout || INITIAL_FLOOR_LAYOUT;
  const prevForFloor = prevLayout[floor] || INITIAL_FLOOR_LAYOUT[floor] || {};

  const nextFloorLayout = {
    ...prevLayout,
    [floor]: {
      ...prevForFloor,
      ...partialLayout,
    },
  };

  const next = saveSettings({ floorLayout: nextFloorLayout });

  logger.info('Floor layout updated', {
    floor,
    columns: next.floorLayout[floor].columns,
    rowsPerCol: next.floorLayout[floor].rowsPerCol,
  });
  broadcastFloorLayout(next.floorLayout);
}

/**
 * Broadcast location icon settings changes to renderer processes
 */
function broadcastLocationIconSettings(locationIcons) {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('location-icon-settings-updated', locationIcons);
  }
}

/**
 * Update floor setting and notify renderer
 */
function updateFloorSetting(floor) {
  const next = saveSettings({ floor });
  logger.info('Floor updated', { floor: next.floor });
  broadcastFloor(next.floor);
}

/**
 * Check if a port is available by attempting to connect to it.
 */
function isPortAvailable(port, host = '127.0.0.1') {
  return new Promise((resolve) => {
    const socket = new net.Socket();
    const timeout = 1000; // 1 second timeout

    socket.setTimeout(timeout);
    
    socket.once('connect', () => {
      socket.destroy();
      resolve(true); // Port is open (service is running)
    });

    socket.once('timeout', () => {
      socket.destroy();
      resolve(false); // Port is not responding
    });

    socket.once('error', (err) => {
      if (err.code === 'ECONNREFUSED') {
        resolve(false); // Port is not open
      } else {
        resolve(false); // Other error, assume not available
      }
    });

    socket.connect(port, host);
  });
}

/**
 * Find an available port within the specified range by checking HTTP connectivity.
 * Returns the first port that responds to HTTP requests successfully.
 */
async function findAvailablePortInRange(minPort, maxPort, path = '/', host = '127.0.0.1') {
  logger.info('Starting port detection', { minPort, maxPort, path, host });
  for (let port = minPort; port <= maxPort; port++) {
    try {
      const url = `http://${host}:${port}${path}`;
      logger.debug('Trying port', { port, url, host });
      
      // Try a quick HTTP request to see if the service is available
      const available = await new Promise((resolve) => {
        const req = http.get(url, { timeout: 2000 }, (res) => {
          // Check if status code is in success range (200-299)
          if (res.statusCode >= 200 && res.statusCode < 300) {
            req.destroy();
            logger.info('Port responded successfully', { port, host, statusCode: res.statusCode, url });
            resolve(true); // Service is responding with success
          } else {
            req.destroy();
            logger.debug('Port responded with non-success status', { port, host, statusCode: res.statusCode, url });
            resolve(false); // Service is responding but with error status
          }
        });

        req.on('error', (err) => {
          logger.debug('Port connection error', { port, host, error: err.code, url });
          resolve(false); // Service is not responding
        });

        req.on('timeout', () => {
          req.destroy();
          logger.debug('Port connection timeout', { port, host, url });
          resolve(false);
        });

        req.setTimeout(2000);
      });

      if (available) {
        logger.info('Found available port in range', { port, minPort, maxPort, path, host, url: `http://${host}:${port}` });
        return port;
      }
    } catch (error) {
      logger.debug('Exception while checking port', { port, host, error: error?.message });
      // Continue to next port
    }
  }

  logger.warn('No available port found in range', { minPort, maxPort, path, host });
  return null;
}

/**
 * Get the base URL for BridgeWebPopper, using port range detection if configured.
 */
async function getBridgeBaseUrl() {
  const settings = loadSettings();
  const portRange = settings.portRanges?.bridge;
  if (portRange && portRange.min && portRange.max) {
    const port = await findAvailablePortInRange(portRange.min, portRange.max, '/api/shops', 'localhost');
    if (port) {
      return `http://localhost:${port}`;
    }
  }

  // Fallback to default
  return 'http://localhost:8090';
}

/**
 * Get the base URL for CMS (WSP), using port range detection if configured.
 */
async function getCmsBaseUrl() {
  const settings = loadSettings();
  const portRange = settings.portRanges?.cms;

  logger.debug('Getting CMS base URL', { portRange });
  if (portRange && portRange.min && portRange.max) {
    // Try both localhost and 127.0.0.1 to handle different network configurations
    const hosts = ['localhost', '127.0.0.1'];
    for (const host of hosts) {
      const port = await findAvailablePortInRange(portRange.min, portRange.max, '/current-timeline', host);
      if (port) {
        const baseUrl = `http://${host}:${port}`;
        logger.info('CMS base URL determined', { baseUrl, port, portRange, host });
        return baseUrl;
      }
    }
    logger.warn('CMS port detection failed for all hosts, using fallback', { portRange });
  } else {
    logger.debug('CMS port range not configured, using fallback');
  }

  // Fallback to default (8080 or 8081 depending on legacy config, here using 8080 to match detection range)
  // Gido originally used 8081, but Gido-Touch uses 8080-8089. We will fallback to 8080.
  // Try both localhost and 127.0.0.1 for fallback
  const fallbackHosts = ['localhost', '127.0.0.1'];
  const fallbackPort = 8080;
  
  for (const host of fallbackHosts) {
    try {
      const testUrl = `http://${host}:${fallbackPort}/current-timeline`;
      const available = await new Promise((resolve) => {
        const req = http.get(testUrl, { timeout: 2000 }, (res) => {
          req.destroy();
          if (res.statusCode >= 200 && res.statusCode < 300) {
            resolve(true);
          } else {
            resolve(false);
          }
        });
        req.on('error', () => resolve(false));
        req.on('timeout', () => {
          req.destroy();
          resolve(false);
        });
        req.setTimeout(2000);
      });
      
      if (available) {
        const fallbackUrl = `http://${host}:${fallbackPort}`;
        logger.info('Using CMS fallback URL (verified)', { fallbackUrl, host });
        return fallbackUrl;
      }
    } catch (error) {
      logger.debug('Fallback host test failed', { host, error: error?.message });
    }
  }
  
  // If all fallback attempts failed, still return localhost:8080 as last resort
  const fallbackUrl = 'http://localhost:8080';
  logger.warn('Using CMS fallback URL (unverified)', { fallbackUrl });
  return fallbackUrl;
}

// Cache for base URLs to avoid repeated port detection
let cachedBridgeBaseUrl = null;
let cachedCmsBaseUrl = null;
let lastPortCheckTime = 0;
const PORT_CHECK_INTERVAL = 30000; // Check every 30 seconds

/**
 * Get cached or fresh Bridge base URL.
 */
async function getCachedBridgeBaseUrl() {
  const now = Date.now();
  if (!cachedBridgeBaseUrl || (now - lastPortCheckTime) > PORT_CHECK_INTERVAL) {
    cachedBridgeBaseUrl = await getBridgeBaseUrl();
    lastPortCheckTime = now;
  }
  return cachedBridgeBaseUrl;
}

/**
 * Get cached or fresh CMS base URL.
 */
async function getCachedCmsBaseUrl() {
  const now = Date.now();
  if (!cachedCmsBaseUrl || (now - lastPortCheckTime) > PORT_CHECK_INTERVAL) {
    logger.info('Refreshing CMS base URL cache', { 
      cached: cachedCmsBaseUrl, 
      lastCheck: lastPortCheckTime,
      interval: PORT_CHECK_INTERVAL 
    });
    cachedCmsBaseUrl = await getCmsBaseUrl();
    lastPortCheckTime = now;
    logger.info('CMS base URL cache updated', { baseUrl: cachedCmsBaseUrl });
  } else {
    logger.debug('Using cached CMS base URL', { baseUrl: cachedCmsBaseUrl });
  }
  return cachedCmsBaseUrl;
}

/**
 * Clear CMS base URL cache to force re-detection on next request.
 */
function clearCmsBaseUrlCache() {
  cachedCmsBaseUrl = null;
  lastPortCheckTime = 0;
  logger.info('CMS base URL cache cleared');
}

/**
 * IPC handler to clear CMS base URL cache (for debugging).
 */
ipcMain.handle('cms:clear-cache', () => {
  clearCmsBaseUrlCache();
  logger.info('CMS cache cleared via IPC');
  return true;
});

/**
 * IPC handler to get current CMS base URL (for debugging).
 */
ipcMain.handle('cms:get-base-url', async () => {
  const baseUrl = await getCachedCmsBaseUrl();
  logger.info('CMS base URL requested via IPC', { baseUrl });
  return baseUrl;
});

/**
 * Simple HTTP GET helper that retrieves JSON from a given URL.
 */
function httpGetJson(url) {
  return new Promise((resolve, reject) => {
    const timeout = 5000; // 5 seconds timeout
    const startTime = Date.now();

    const req = http.get(url, (res) => {
      if (res.statusCode < 200 || res.statusCode >= 300) {
        const error = new Error(`HTTP ${res.statusCode}`);
        logger.warn('HTTP request failed', {
          url,
          statusCode: res.statusCode,
          durationMs: Date.now() - startTime,
        });
        reject(error);
        res.resume();
        return;
      }

      let data = '';
      res.setEncoding('utf8');
      res.on('data', (chunk) => {
        data += chunk;
      });
      res.on('end', () => {
        try {
          const json = JSON.parse(data);
          const duration = Date.now() - startTime;
          logger.debug('HTTP request succeeded', {
            url,
            durationMs: duration,
            dataSize: data.length,
          });
          resolve(json);
        } catch (err) {
          logger.error('Failed to parse JSON response', {
            url,
            error: err?.message,
            durationMs: Date.now() - startTime,
          });
          reject(err);
        }
      });
    });

    req.on('error', (err) => {
      logger.error('HTTP request error', {
        url,
        error: err?.message,
        durationMs: Date.now() - startTime,
      });
      reject(err);
    });

    // Set timeout
    req.setTimeout(timeout, () => {
      req.destroy();
      const error = new Error(`Request timeout after ${timeout}ms`);
      logger.error('HTTP request timeout', {
        url,
        timeout,
        durationMs: Date.now() - startTime,
      });
      reject(error);
    });
    req.end();
  });
}

/**
 * Convert a Windows file path to a file:// URL string.
 */
function toFileUrl(winPath) {
  try {
    return pathToFileURL(winPath).toString();
  } catch (error) {
    logger.warn('Failed to convert path to file URL, using fallback', {
      error: error?.message,
      winPath,
    });
    const normalized = winPath.replace(/\\/g, '/');
    return `file:///${normalized}`;
  }
}

/**
 * Create the small startup patch window.
 * This window appears first and shows update progress.
 */
function createPatchWindow() {
  if (patchWindow && !patchWindow.isDestroyed()) {
    logger.debug('Patch window already exists, focusing');
    patchWindow.focus();
    return;
  }

  logger.info('Creating patch window');

  patchWindow = new BrowserWindow({
    resizable: false,
    frame: false,
    transparent: true,
    backgroundColor: '#00000000',
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // Use #patch hash so renderer can show PatchScreen instead of app UI
  patchWindow.loadURL(`${rendererBaseUrl}#patch`);

  patchWindow.once('ready-to-show', () => {
    if (patchWindow) {
      logger.info('Patch window ready to show');
      patchWindow.show();
    }
  });

  patchWindow.on('closed', () => {
    logger.info('Patch window closed');
    patchWindow = null;
  });
}

/**
 * Create the main application window (fullscreen UI).
 */
function createMainWindow() {
  if (mainWindow && !mainWindow.isDestroyed()) {
    logger.debug('Main window already exists, focusing');
    mainWindow.focus();
    return;
  }

  mainWindow = new BrowserWindow({
    width: 1920,
    height: 1080,
    fullscreen: true,
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      nodeIntegration: false,
      contextIsolation: true,
      devTools: true, // Enable dev tools even in production for debugging
      // Allow loading local file:// URLs for media assets
      webSecurity: false, // Required to load local file:// URLs from CMS
    },
    alwaysOnTop: true,
  });

  // Ensure it stays on top even if other apps try to take focus
  mainWindow.setAlwaysOnTop(true, 'screen-saver');

  // Enable F12 shortcut to toggle dev tools
  // Enable Ctrl+R shortcut to reload in dev environment
  mainWindow.webContents.on('before-input-event', (event, input) => {
    if (input.key === 'F12') {
      mainWindow.webContents.toggleDevTools();
    }
    // Ctrl+R to reload in dev environment
    if (isDev && input.control && (input.key === 'r' || input.key === 'R')) {
      event.preventDefault();
      mainWindow.webContents.reload();
      logger.info('Window reloaded via Ctrl+R');
    }
  });

  mainWindow.loadURL(rendererBaseUrl);

  // Send current floor setting after renderer has finished loading
  const settings = loadSettings();
  mainWindow.webContents.on('did-finish-load', () => {
    logger.info('Main window finished loading, broadcasting settings', {
      floor: settings.floor,
    });
    broadcastFloor(settings.floor);
    broadcastLocationIconSettings(settings.locationIcons);
    broadcastFloorLayout(settings.floorLayout);
    broadcastGenreMappings(settings.genreMappings);
    broadcastShopSettings(settings.shopSettings);
  });

  mainWindow.on('closed', () => {
    logger.info('Main window closed');
    mainWindow = null;
  });
}

/**
 * Build application menu including floor setting and manual update entries.
 */
function createAppMenu() {
  const settings = loadSettings();
  logger.info('Creating application menu', {
    initialFloor: settings.floor,
  });

  const template = [
    {
      label: 'ファイル',
      submenu: [
        {
          role: 'quit',
          label: '終了',
        },
      ],
    },
    {
      label: '設定',
      submenu: [
        {
          label: '設定画面を開く',
          click: () => {
            logger.info('Unified settings screen menu clicked');
            if (mainWindow && !mainWindow.isDestroyed()) {
              mainWindow.webContents.send('open-settings');
            }
          },
        },
        { type: 'separator' },
        {
          label: '開発者ツール',
          accelerator: 'F12',
          click: () => {
            logger.info('Developer tools toggled');
            if (mainWindow && !mainWindow.isDestroyed()) {
              mainWindow.webContents.toggleDevTools();
            }
          },
        },
      ],
    },
    {
      label: 'ヘルプ',
      submenu: [
        {
          label: 'バージョン情報',
          click: () => {
            logger.info('Version info requested');
            if (mainWindow && !mainWindow.isDestroyed()) {
              mainWindow.webContents.send('open-version-info');
            }
          },
        },
        { type: 'separator' },
        {
          label: '更新を確認（手動）',
          click: () => {
            logger.info('Manual update check requested');
            checkForUpdates(true); // manual check
          },
        },
        {
          label: '今すぐ更新（ワンクリック）',
          click: () => {
            logger.info('One-click update requested');
            oneClickUpdate(); // one-click automatic update
          },
        },
      ],
    },
  ];

  const menu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(menu);
}

/**
 * IPC handlers for settings and app info.
 */
ipcMain.handle('settings:get-floor', () => {
  const settings = loadSettings();
  logger.debug('IPC settings:get-floor', { floor: settings.floor });
  return settings.floor;
});

ipcMain.handle('settings:get-floor-layout', () => {
  const settings = loadSettings();
  logger.debug('IPC settings:get-floor-layout');
  return settings.floorLayout || INITIAL_FLOOR_LAYOUT;
});

ipcMain.handle('settings:save-floor-layout', (_event, floorLayout) => {
  logger.info('IPC settings:save-floor-layout');
  const settings = saveSettings({ floorLayout });
  broadcastFloorLayout(settings.floorLayout);
  return settings.floorLayout;
});

ipcMain.handle('get-genre-mappings', () => {
  const settings = loadSettings();
  logger.debug('IPC get-genre-mappings');
  return settings.genreMappings || INITIAL_GENRE_MAPPINGS;
});

ipcMain.handle('save-genre-mappings', (_event, genreMappings) => {
  logger.info('IPC save-genre-mappings');
  const settings = saveSettings({ genreMappings });
  broadcastGenreMappings(settings.genreMappings);
  return settings.genreMappings;
});

ipcMain.handle('get-shop-settings', () => {
  const settings = loadSettings();
  logger.debug('IPC get-shop-settings');
  return settings.shopSettings || {};
});

ipcMain.handle('save-shop-settings', (_event, shopSettings) => {
  logger.info('IPC save-shop-settings');
  const settings = saveSettings({ shopSettings });
  broadcastShopSettings(settings.shopSettings);
  return settings.shopSettings;
});

ipcMain.handle('debug:get-settings-status', () => {
  const settingsPath = getSettingsPath();
  const exists = fs.existsSync(settingsPath);
  let content = null;
  let parsed = null;
  let error = null;

  if (exists) {
    try {
      let raw = fs.readFileSync(settingsPath, 'utf-8');
      if (raw.charCodeAt(0) === 0xFEFF) { // BOM除去
        raw = raw.slice(1);
      }
      content = raw.substring(0, 200) + (raw.length > 200 ? '...' : '');
      parsed = JSON.parse(raw);
    } catch (e) {
      error = e.message;
    }
  }

  const loadedSettings = loadSettings();

  return {
    path: settingsPath,
    exists,
    contentPreview: content,
    jsonParseResult: parsed ? {
      currentFloorSetting: parsed.floor,
      typeOfFloor: typeof parsed.floor
    } : null,
    loadSettingsResult: {
      currentFloorSetting: loadedSettings.floor,
      typeOfFloor: typeof loadedSettings.floor
    },
    internalDebug: lastLoadSettingsDebug,
    error
  };
});

ipcMain.handle('get-app-version', () => {
  const version = app.getVersion();
  logger.debug('IPC get-app-version', { version });
  return version;
});

ipcMain.handle('get-latest-version-info', async () => {
  logger.debug('IPC get-latest-version-info');
  const info = await getLatestVersionInfo();
  return info;
});

ipcMain.handle('get-bridge-base-url', async () => {
  logger.debug('IPC get-bridge-base-url');
  const url = await getCachedBridgeBaseUrl();
  return url;
});

/**
 * IPC handlers for location icon settings.
 */
ipcMain.handle('get-location-icon-settings', () => {
  const settings = loadSettings();
  logger.debug('IPC get-location-icon-settings');
  return settings.locationIcons;
});

ipcMain.handle('save-location-icon-settings', (_event, locationIcons) => {
  logger.info('IPC save-location-icon-settings', {
    hasSpeechBubble: !!locationIcons?.speechBubble,
    hasLocation: !!locationIcons?.location,
  });
  const settings = saveSettings({ locationIcons });
  broadcastLocationIconSettings(settings.locationIcons);
  return settings.locationIcons;
});

/**
 * Get images directory path (userData/images)
 */
function getImagesDirectory() {
  const imagesDir = path.join(app.getPath('userData'), 'images');
  if (!fs.existsSync(imagesDir)) {
    fs.mkdirSync(imagesDir, { recursive: true });
  }
  return imagesDir;
}

/**
 * Save SVG file from data URL to disk
 */
function saveSvgFile(dataUrl, filename) {
  try {
    // Extract base64 data from data URL
    const base64Data = dataUrl.replace(/^data:image\/svg\+xml;base64,/, '');
    const buffer = Buffer.from(base64Data, 'base64');
    const filePath = path.join(getImagesDirectory(), filename);
    fs.writeFileSync(filePath, buffer);
    return filePath;
  } catch (error) {
    logger.error('Failed to save SVG file', {
      error: error?.message,
      filename,
    });
    throw error;
  }
}

/**
 * Read SVG file and return as data URL
 */
function readSvgFileAsDataUrl(filePath) {
  try {
    if (!fs.existsSync(filePath)) {
      return null;
    }
    const buffer = fs.readFileSync(filePath);
    const base64 = buffer.toString('base64');
    return `data:image/svg+xml;base64,${base64}`;
  } catch (error) {
    logger.error('Failed to read SVG file', {
      error: error?.message,
      filePath,
    });
    return null;
  }
}

/**
 * IPC handlers for image settings.
 */
ipcMain.handle('get-image-settings', () => {
  const settings = loadSettings();
  logger.debug('IPC get-image-settings');
  
  // Convert file paths to data URLs if they exist
  const imageSettings = settings.imageSettings || {
    floorMaps: { '1F': '', '2F': '', '3F': '', '4F': '' },
    openTimeImage: '',
  };
  
  const result = {
    floorMaps: {},
    openTimeImage: '',
  };
  
  // Convert floor map paths to data URLs
  for (const floor of ['1F', '2F', '3F', '4F']) {
    const filePath = imageSettings.floorMaps?.[floor];
    if (filePath && filePath.startsWith('file://')) {
      const localPath = filePath.replace('file://', '');
      const dataUrl = readSvgFileAsDataUrl(localPath);
      result.floorMaps[floor] = dataUrl || '';
    } else if (filePath && filePath.startsWith('data:')) {
      // Already a data URL
      result.floorMaps[floor] = filePath;
    } else {
      result.floorMaps[floor] = '';
    }
  }
  
  // Convert open time image path to data URL
  const openTimePath = imageSettings.openTimeImage;
  if (openTimePath && openTimePath.startsWith('file://')) {
    const localPath = openTimePath.replace('file://', '');
    const dataUrl = readSvgFileAsDataUrl(localPath);
    result.openTimeImage = dataUrl || '';
  } else if (openTimePath && openTimePath.startsWith('data:')) {
    result.openTimeImage = openTimePath;
  } else {
    result.openTimeImage = '';
  }
  
  return result;
});

ipcMain.handle('save-image-settings', async (_event, imageSettings) => {
  logger.info('IPC save-image-settings');
  
  try {
    const savedSettings = {
      floorMaps: {},
      openTimeImage: '',
    };
    
    // Save floor maps
    for (const floor of ['1F', '2F', '3F', '4F']) {
      const dataUrl = imageSettings.floorMaps?.[floor] || '';
      if (dataUrl && dataUrl.startsWith('data:')) {
        const filename = `floor-${floor}-map.svg`;
        const filePath = saveSvgFile(dataUrl, filename);
        savedSettings.floorMaps[floor] = `file://${filePath}`;
      } else if (dataUrl) {
        // Already a file path, keep it
        savedSettings.floorMaps[floor] = dataUrl;
      } else {
        savedSettings.floorMaps[floor] = '';
      }
    }
    
    // Save open time image
    const openTimeDataUrl = imageSettings.openTimeImage || '';
    if (openTimeDataUrl && openTimeDataUrl.startsWith('data:')) {
      const filename = 'open-time.svg';
      const filePath = saveSvgFile(openTimeDataUrl, filename);
      savedSettings.openTimeImage = `file://${filePath}`;
    } else if (openTimeDataUrl) {
      savedSettings.openTimeImage = openTimeDataUrl;
    } else {
      savedSettings.openTimeImage = '';
    }
    
    const settings = saveSettings({ imageSettings: savedSettings });
    
    // Broadcast to main window if it exists
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('image-settings-updated', settings.imageSettings);
    }
    
    return settings.imageSettings;
  } catch (error) {
    logger.error('Failed to save image settings', {
      error: error?.message,
    });
    throw error;
  }
});

/**
 * IPC handler for WSP current asset.
 * Uses /current-timeline, extracts the first media asset,
 * and returns a simplified object for the renderer.
 */
ipcMain.handle('wsp:get-current-asset', async () => {
  try {
    const baseUrl = await getCachedCmsBaseUrl();
    const url = `${baseUrl}/current-timeline`;
    logger.info('wsp:get-current-asset: requesting', { url, baseUrl });
    const json = await httpGetJson(url);

    if (!json || !json.current_timeline) {
      logger.warn('wsp:get-current-asset: current_timeline is missing');
      return null;
    }

    const tl = json.current_timeline;
    // Support both old format (tl.media_assets) and new format (tl.data.media_assets)
    const data = tl.data || tl;
    const assets = data.media_assets || [];
    if (!Array.isArray(assets) || assets.length === 0) {
      logger.warn('wsp:get-current-asset: media_assets is empty', {
        hasData: !!tl.data,
        hasMediaAssets: !!(tl.data?.media_assets || tl.media_assets),
      });
      return null;
    }

    const asset = assets[0];

    // Determine media type from asset properties or URL extension
    const mediaType = asset.mediaType || asset.type || '';
    // Support both 'url' and 'localPath' fields
    const assetPath = asset.url || asset.localPath || '';
    const pathLower = assetPath.toLowerCase();
    
    // Infer media type from URL extension if not provided
    let inferredMediaType = mediaType;
    if (!inferredMediaType) {
      if (pathLower.match(/\.(mp4|webm|ogg|mov|avi|mkv)$/)) {
        inferredMediaType = 'video';
      } else if (pathLower.match(/\.(jpg|jpeg|png|gif|bmp|webp|svg)$/)) {
        inferredMediaType = 'image';
      }
    }

    // Convert localPath or url to file:// URL
    let src = '';
    if (assetPath) {
      if (assetPath.startsWith('http://') || assetPath.startsWith('https://')) {
        src = assetPath;
      } else {
        src = toFileUrl(assetPath);
      }
    }

    // Support both old format (tl.media_names) and new format (data.media_names)
    const mediaNames = data.media_names || tl.media_names || [];
    // Support both old format (tl.start_time) and new format (data.start_time)
    const startTime = data.start_time || tl.start_time || '';
    const endTime = data.end_time || tl.end_time || '';

    logger.info('wsp:get-current-asset: returning first asset', {
      assetId: asset.id,
      path: assetPath,
      src,
      mediaType: inferredMediaType,
      hasData: !!tl.data,
    });

    return {
      id: asset.id,
      src: src,
      duration: asset.duration,
      width: asset.width,
      height: asset.height,
      name:
        Array.isArray(mediaNames) && mediaNames.length > 0
          ? mediaNames[0]
          : '',
      startTime: startTime,
      endTime: endTime,
      mediaType: inferredMediaType,
      type: asset.type,
    };
  } catch (error) {
    logger.error('wsp:get-current-asset failed', {
      error: error?.message,
    });
    // Clear cache on connection error to force re-detection
    if (error?.message?.includes('ECONNREFUSED') || error?.message?.includes('timeout') || error?.message?.includes('ENOTFOUND')) {
      logger.warn('Connection error detected, clearing CMS cache for re-detection');
      clearCmsBaseUrlCache();
    }
    return null;
  }
});

/**
 * IPC handler: return raw /current-timeline JSON.
 */
ipcMain.handle('wsp:get-current-timeline', async () => {
  try {
    const baseUrl = await getCachedCmsBaseUrl();
    const url = `${baseUrl}/current-timeline`;
    const json = await httpGetJson(url);
    logger.debug('wsp:get-current-timeline: success');
    return json || null;
  } catch (error) {
    logger.error('wsp:get-current-timeline failed', {
      error: error?.message,
    });
    // Clear cache on connection error to force re-detection
    if (error?.message?.includes('ECONNREFUSED') || error?.message?.includes('timeout') || error?.message?.includes('ENOTFOUND')) {
      logger.warn('Connection error detected, clearing CMS cache for re-detection');
      clearCmsBaseUrlCache();
    }
    return null;
  }
});

/**
 * IPC handler: return raw /timeline or /timeline?hour=... JSON.
 */
ipcMain.handle('wsp:get-timeline', async (_event, options) => {
  try {
    const hour =
      options && typeof options.hour === 'number' && !Number.isNaN(options.hour)
        ? options.hour
        : undefined;

    const cmsBaseUrl = await getCachedCmsBaseUrl();
    const baseUrl = `${cmsBaseUrl}/timeline`;
    const url = hour != null ? `${baseUrl}?hour=${hour}` : baseUrl;

    const json = await httpGetJson(url);
    logger.debug('wsp:get-timeline: success', { hour });
    return json || null;
  } catch (error) {
    logger.error('wsp:get-timeline failed', {
      error: error?.message,
    });
    // Clear cache on connection error to force re-detection
    if (error?.message?.includes('ECONNREFUSED') || error?.message?.includes('timeout') || error?.message?.includes('ENOTFOUND')) {
      logger.warn('Connection error detected, clearing CMS cache for re-detection');
      clearCmsBaseUrlCache();
    }
    return null;
  }
});

/**
 * IPC handler to receive logs from renderer process.
 * The preload exposes window.logger which sends log-message IPC.
 */
ipcMain.on('log-message', (_event, payload) => {
  try {
    logger.logFromRenderer(payload || {});
  } catch (error) {
    logger.error('Failed to handle log-message IPC', {
      error: error?.message,
    });
  }
});

// Floor change from renderer
ipcMain.on('menu:set-floor', (_event, floorId) => {
  updateFloorSetting(floorId);
});

// Manual update check
ipcMain.on('menu:check-updates', () => {
  checkForUpdates(true);
});

// Startup update check ready (from PatchScreen)
ipcMain.on('updater:check-for-updates-ready', () => {
  logger.info('Renderer ready for updates, starting initial check');
  checkForUpdates(false);
});

// Startup wait completed (from PatchScreen)
ipcMain.on('startup-wait-completed', () => {
  logger.info('Startup wait completed, switching to main window');
  
  if (patchWindow && !patchWindow.isDestroyed()) {
    patchWindow.close();
  }
  
  createMainWindow();
});

// One-click update
ipcMain.on('menu:one-click-update', () => {
  oneClickUpdate();
});

// Quit app
ipcMain.on('menu:quit', () => {
  app.quit();
});

/**
 * Global error handlers for main process.
 */
process.on('uncaughtException', (error) => {
  logger.fatal('Uncaught exception in main process', {
    error: error?.message,
    stack: error?.stack,
  });
});

process.on('unhandledRejection', (reason) => {
  logger.fatal('Unhandled promise rejection in main process', {
    reason: String(reason),
  });
});

/**
 * App ready event.
 */
app.whenReady().then(() => {
  logger.configureLogger();
  logger.info('Application starting', {
    env: process.env.NODE_ENV || 'production',
    isDev,
  });

  // In development mode, skip update check and open main window directly
  if (isDev) {
    logger.info('Development mode: skipping update check');
    createAppMenu();
    createMainWindow();
    return;
  }

  createPatchWindow();
  createAppMenu();

  // Initialize autoUpdater with patch + main window references
  initAutoUpdater({
    getPatchWindow: () => patchWindow,
    createMainWindow,
  });

  // Startup update check is now triggered by renderer via IPC (updater:check-for-updates-ready)
  // to avoid race conditions where events are sent before listeners are registered.
  // checkForUpdates(false);

  app.on('activate', () => {
    if (process.platform !== 'darwin') return;

    // macOS: recreate main window if no windows are open
    if (BrowserWindow.getAllWindows().length === 0) {
      logger.info('App activated on macOS with no windows, creating main window');
      createMainWindow();
    }
  });
});

/**
 * Quit when all windows are closed.
 * Except macOS where apps usually stay active.
 */
app.on('window-all-closed', () => {
  logger.info('All windows closed', { platform: process.platform });
  if (process.platform !== 'darwin') app.quit();
});